### ISSUE TITLE
Reverb

### ISSUE THREAD

**Issue by enzor** [maxl0rd/standingwave3#23]
More a request than an issue.
Do you think is possible to implement a freeverb function in the awave.c module ?
i'm starting to working on it based on this library -> https://ccrma.stanford.edu/~travissk/faustflash/ , but seems that i'm hitting a dead point (standingwave works in a radical different way than faust, or the cpp version of it ).
Most of it, would the computational cost be sustainable, or would send the cpu usage to skyrocket levels?

**Comment by maxl0rd** [comment]
Hi

This is probably doable. I'm sure it will take some tinkering to work that library into the SW3 model. SW3 works by processing entire sample buffers at a time, rather than a "one tick at a time" model like most audio engines. The reason for this is that the function call overhead in ActionScript is enormous. If you call a function for every sample frame, it just doesn't work. So anything that you want to port should be rewritten so that it can process a entire sample buffer in a single function, like the existing code. Hope that makes sense. The preprocessor is your friend here.

Max

**Comment by enzor** [comment]
this definitely does make sense.
i will try to stub something and if i have any problem i will get back to you! thank you!
